### ISSUE TITLE
Option to enable geo VPN 

### ISSUE THREAD

**Issue by mk-avx** [terraform-aviatrix-modules/terraform-aviatrix-aws-uservpn#4]
Is it possible to add the [geo](https://registry.terraform.io/providers/AviatrixSystems/aviatrix/latest/docs/resources/aviatrix_geo_vpn) vpn option

**Comment by Dennizz** [comment]
The module is written to deploy VPN gateways in a single region. As the geo vpn resource actually is used to combine ELB's of multiple regions, it doesn't make sense to include it in the module. It would make more sense to do something like this (see 2.0.0 changes):

```
module "vpn_1" {
  source  = "terraform-aviatrix-modules/aws-uservpn/aviatrix"
  version = "2.0.0"

  region = "eu-central-1"
  <etc>
}

module "vpn_2" {
  source  = "terraform-aviatrix-modules/aws-uservpn/aviatrix"
  version = "2.0.0"

  region = "us-east-1"
  <etc>
}

resource "aviatrix_geo_vpn" "test_geo_vpn" {
  cloud_type    = 1
  account_name  = "devops-aws"
  service_name  = "vpn"
  domain_name   = "aviatrix.live"
  elb_dns_names = [
    module.vpn_1.elb_dns_name,
    module.vpn_2.elb_dns_name,
  ]
}
