### ISSUE TITLE
remove the transit attachment from the spoke gw resource

### ISSUE THREAD

**Issue by mk-avx** [terraform-aviatrix-modules/terraform-aviatrix-aws-uservpn#5]
remove the transit attachment from the spoke gw resource since its being deprecated https://registry.terraform.io/providers/AviatrixSystems/aviatrix/latest/docs/resources/aviatrix_spoke_transit_attachment

**Comment by Dennizz** [comment]
This is solved by using the mc-spoke module in conjunction with this module, in stead of embedding it. This allows full spoke capabilities.
